# Generated by Django 4.0.4 on 2022-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='times_saved',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
